# Generated by Django 3.2.5 on 2021-08-02 21:16

import csvapp.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csvfiles', validators=[csvapp.validators.csv_file_validator])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('column_name', models.CharField(default='Free', max_length=25)),
            ],
        ),
    ]
